23 add legend and guidelines for using the app
maxellmilay/finite-automata-visualizer pull request #27
Opened 2024-05-27 15:30 UTC by yunjin08

lesgo bitch

2024-05-28 12:19 UTC, maxellmilay commented on components/LegendPanel.tsx
> +];
@yunjin08 I suggest we put this in a separate file, inside a folder named constants

2024-05-28 12:19 UTC, maxellmilay commented on components/LegendPanel.tsx
> +]
@yunjin08 also put this in a constants file

2024-05-28 12:20 UTC, maxellmilay requested changes
Please address the comments, thank you!

2024-05-29 04:07 UTC, yunjin08 commented on components/LegendPanel.tsx
> +];
@maxellmilay done aydol

2024-05-29 04:11 UTC, maxellmilay approved these changes
@yunjin08 LGTM :fire:

2024-05-29 04:11 UTC, merged